name: Jekyll site CI

on:
  push:
    branches:
      - main

jobs:
  jekyll:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Build site with Jekyll
        run: bundle exec jekyll build
